# netlify.toml
[build]
  command = "npm run build" # Your React build command
  publish = "dist" # The directory where your built React app is located (e.g., 'build' for Create React App)

[build.environment]
  GAS_V2_WEB_APP_URL = "https://script.google.com/macros/s/AKfycbz_h3_78xJGgVkmgsMcGBcKmkVg3oMYjAZWTosC625xK0B1wbsWLkcaj2GANEIGQHll/exec"
  
[functions]
  directory = "netlify/functions" # Directory where your Netlify Functions are located